export const MOVEMENT_LIMITATIONS_BY_AREA: Record<string, { id: string; label: string }[]> = {
  knee: [
    { id: "squatting", label: "Squatting" },
    { id: "going_up_stairs", label: "Going up stairs" },
    { id: "going_down_stairs", label: "Going down stairs" },
    { id: "running", label: "Running" },
    { id: "walking", label: "Walking" },
    { id: "lunging", label: "Lunging" },
    { id: "all_of_the_above", label: "All of the above" },
  ],
  shoulder: [
    { id: "reaching_overhead", label: "Reaching overhead" },
    { id: "reaching_behind_back", label: "Reaching behind back" },
    { id: "pushing", label: "Pushing movements" },
    { id: "pulling", label: "Pulling movements" },
    { id: "lifting", label: "Lifting objects" },
    { id: "sleeping_on_side", label: "Sleeping on this side" },
    { id: "all_of_the_above", label: "All of the above" },
  ],
  lower_back: [
    { id: "bending_forward", label: "Bending forward" },
    { id: "standing_up", label: "Standing up from sitting" },
    { id: "twisting", label: "Twisting or rotating" },
    { id: "lifting", label: "Lifting objects" },
    { id: "sitting_long", label: "Sitting for long periods" },
    { id: "walking", label: "Walking" },
    { id: "all_of_the_above", label: "All of the above" },
  ],
  neck: [
    { id: "turning_head", label: "Turning head side to side" },
    { id: "looking_up", label: "Looking up" },
    { id: "looking_down", label: "Looking down" },
    { id: "tilting_head", label: "Tilting head to side" },
    { id: "sleeping", label: "Sleeping comfortably" },
    { id: "all_of_the_above", label: "All of the above" },
  ],
  hip: [
    { id: "walking", label: "Walking" },
    { id: "climbing_stairs", label: "Climbing stairs" },
    { id: "squatting", label: "Squatting" },
    { id: "sitting_long", label: "Sitting for long periods" },
    { id: "crossing_legs", label: "Crossing legs" },
    { id: "getting_in_out_car", label: "Getting in/out of car" },
    { id: "all_of_the_above", label: "All of the above" },
  ],
  ankle_foot: [
    { id: "walking", label: "Walking" },
    { id: "running", label: "Running" },
    { id: "going_up_stairs", label: "Going up stairs" },
    { id: "going_down_stairs", label: "Going down stairs" },
    { id: "standing_long", label: "Standing for long periods" },
    { id: "pointing_toes", label: "Pointing toes" },
    { id: "all_of_the_above", label: "All of the above" },
  ],
  elbow: [
    { id: "gripping", label: "Gripping objects" },
    { id: "twisting_arm", label: "Twisting arm (opening jars)" },
    { id: "pushing", label: "Pushing" },
    { id: "pulling", label: "Pulling" },
    { id: "lifting", label: "Lifting" },
    { id: "all_of_the_above", label: "All of the above" },
  ],
  wrist_hand: [
    { id: "gripping", label: "Gripping objects" },
    { id: "twisting", label: "Twisting motions" },
    { id: "typing", label: "Typing" },
    { id: "writing", label: "Writing" },
    { id: "lifting", label: "Lifting" },
    { id: "all_of_the_above", label: "All of the above" },
  ],
  upper_back: [
    { id: "sitting", label: "Sitting for long periods" },
    { id: "reaching", label: "Reaching forward" },
    { id: "twisting", label: "Twisting" },
    { id: "breathing_deeply", label: "Breathing deeply" },
    { id: "sleeping", label: "Sleeping" },
    { id: "all_of_the_above", label: "All of the above" },
  ],
  quadriceps: [
    { id: "squatting", label: "Squatting" },
    { id: "going_up_stairs", label: "Going up stairs" },
    { id: "running", label: "Running" },
    { id: "lunging", label: "Lunging" },
    { id: "kneeling", label: "Kneeling" },
    { id: "all_of_the_above", label: "All of the above" },
  ],
  hamstrings: [
    { id: "bending_forward", label: "Bending forward" },
    { id: "running", label: "Running" },
    { id: "sitting_long", label: "Sitting for long periods" },
    { id: "stretching", label: "Stretching" },
    { id: "kicking", label: "Kicking motions" },
    { id: "all_of_the_above", label: "All of the above" },
  ],
  calf: [
    { id: "walking", label: "Walking" },
    { id: "running", label: "Running" },
    { id: "going_up_stairs", label: "Going up stairs" },
    { id: "standing_on_toes", label: "Standing on toes" },
    { id: "jumping", label: "Jumping" },
    { id: "all_of_the_above", label: "All of the above" },
  ],
};

export function getMovementOptionsForArea(areaName: string): { id: string; label: string }[] {
  const normalizedName = areaName.toLowerCase().replace(/\s+/g, '_');
  return MOVEMENT_LIMITATIONS_BY_AREA[normalizedName] || [];
}
