import { Pool, neonConfig } from "@neondatabase/serverless";
import ws from "ws";
neonConfig.webSocketConstructor = ws;
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const outcomes: any[] = [
  { body_area_id: 13, name: "quad_keep_moving", display_name: "Keep moving", priority: 1, is_active: true, severity_min: 1, severity_max: 3, training_impact: "normal", movement_impact: "none", triggers_follow_up: false, follow_up_question: null, follow_up_answers: null, movement_question: null, movement_options: null, whats_going_on: "Your quad is flagging some mild discomfort but not enough to change your training. This is common after heavy leg sessions or a change in training volume. At this level it is usually delayed onset muscle soreness or mild tendon irritation rather than anything structural.", training_guidance: "Train as normal. Be mindful of how the quad feels during squatting and lunging movements. If anything causes a noticeable spike beyond normal training soreness, reduce load or depth slightly. Everything else continues as planned.", daily_movement: "Keep moving normally. Stairs and walking are fine. If the quad feels stiff first thing in the morning, a gentle walk and some easy leg swings will help loosen it up.", desk_work_tips: "If you sit for long periods, stand up and do a few gentle quad stretches periodically. Prolonged sitting with the knee bent can contribute to quad tightness and mild discomfort over the course of a day.", things_to_watch: "If the discomfort increases significantly, starts to feel sharp, causes visible swelling in the thigh, or begins to affect your ability to extend the knee fully, update your assessment.", check_in_again: "Check back in 7 days, or sooner if things change.", show_programme_impact: false, programme_impact_summary: null, flagging_movement_patterns: null, flagging_equipment: null, flagging_level: null, flagging_mechanics: null, flagging_muscles: null, flagging_exclude_tags: null, flagging_note: null, substitution_rules: null, recommend_recovery_programme: false, recovery_programme_id: null, recovery_programme_reason: null, restore_on_reassessment: true, reassess_in_days: 7 },
  { body_area_id: 13, name: "quad_modify", display_name: "Modify your training", priority: 2, is_active: true, severity_min: 4, severity_max: 7, training_impact: "limited", movement_impact: "slight", triggers_follow_up: true, follow_up_question: "Which movements cause discomfort?", follow_up_answers: ["Squatting", "Lunging", "Going up or down stairs"], movement_question: "Does this limit how you move?", movement_options: ["Squatting", "Lunging", "Going up or down stairs", "Straightening the knee fully", "Running or walking fast", "All of the above"], whats_going_on: "Your quad is uncomfortable enough to need some training adjustment. Pain in the front of the thigh during squatting and knee extension is usually the quad tendon or the muscle itself reacting to training load. Reducing depth and load while keeping the movement pattern going is the right approach.", training_guidance: "Reduce squat depth and load for now. Partial range squats and box squats are fine. Avoid heavy leg press at full depth. Lunges can usually be kept in at reduced load. Hip hinge movements like deadlifts are completely unaffected as they load the posterior chain rather than the quad. Upper body training is completely unaffected.", daily_movement: "Stairs may feel uncomfortable, particularly going down. Take them slowly and lead with the less affected leg where possible. Walking on flat ground is fine.", desk_work_tips: "Prolonged sitting can cause the quad tendon to stiffen. Stand up and gently straighten the knee every hour. Avoid sitting with the knee very bent for long periods.", things_to_watch: "If the pain becomes sharp and constant rather than load-related, if you notice visible swelling in the thigh, if the knee begins to feel unstable, or if you cannot fully extend the knee, update your assessment.", check_in_again: "Check back in 5 days, or sooner if things change.", show_programme_impact: true, programme_impact_summary: "Quad loading movements have been flagged. Hip hinge and upper body training are unaffected.", flagging_movement_patterns: ["Squat", "Lunge", "Knee Extension"], flagging_equipment: ["Barbell"], flagging_level: null, flagging_mechanics: null, flagging_muscles: null, flagging_exclude_tags: null, flagging_note: "User has quad pain - deep knee extension loading movements flagged", substitution_rules: JSON.stringify({ allowedPatterns: ["Hip Hinge", "Hip Extension", "Horizontal Push", "Horizontal Pull", "Vertical Push", "Vertical Pull", "Core Anti-Extension", "Core Anti-Rotation"], substituteExerciseIds: [] }), recommend_recovery_programme: false, recovery_programme_id: null, recovery_programme_reason: null, restore_on_reassessment: true, reassess_in_days: 5 },
  { body_area_id: 13, name: "quad_seek_assessment", display_name: "Get this looked at", priority: 1, is_active: true, severity_min: 8, severity_max: 10, training_impact: "cannot_train", movement_impact: "significant", triggers_follow_up: true, follow_up_question: "Which movements cause discomfort?", follow_up_answers: ["Squatting", "Lunging", "Going up or down stairs", "Straightening the knee fully", "All of the above"], movement_question: "Does this limit how you move?", movement_options: ["Squatting", "Lunging", "Going up or down stairs", "Straightening the knee fully", "Running or walking fast", "All of the above"], whats_going_on: "Your quad is reporting significant pain. At this level, particularly if it is affecting daily activities like walking or climbing stairs, this needs professional assessment before returning to any lower body training.", training_guidance: "Avoid all loaded quad work until you have been assessed. Upper body training is completely fine. Hip hinge movements can be tested carefully if they do not cause any quad discomfort. Getting the quad assessed is the priority.", daily_movement: "Move gently. Avoid any activity that significantly increases the pain. If walking is painful, minimise it and rest. If the thigh is swollen or bruised, get assessed urgently.", desk_work_tips: "Keep the leg relatively comfortable when sitting. Avoid positions that increase pain. Getting up gently and moving briefly every 30 minutes prevents the area from stiffening up further.", things_to_watch: "Seek urgent assessment if you experience any of the following: significant swelling or bruising in the thigh, inability to extend the knee at all, a pop or snap sensation when the injury occurred, or pain that came on suddenly from a direct impact or sprint.", check_in_again: "Check back in 3 days, or sooner if things change.", show_programme_impact: true, programme_impact_summary: "All quad loading is on hold until you have been assessed. Upper body training is unaffected.", flagging_movement_patterns: ["Squat", "Lunge", "Knee Extension", "Knee Flexion"], flagging_equipment: null, flagging_level: null, flagging_mechanics: null, flagging_muscles: null, flagging_exclude_tags: null, flagging_note: "User has high severity quad pain - all lower body loading flagged", substitution_rules: JSON.stringify({ allowedPatterns: ["Horizontal Push", "Horizontal Pull", "Vertical Push", "Vertical Pull", "Core Anti-Extension", "Core Anti-Rotation"], substituteExerciseIds: [] }), recommend_recovery_programme: true, recovery_programme_id: null, recovery_programme_reason: "High severity quad pain - professional assessment required", restore_on_reassessment: true, reassess_in_days: 3 },
];
async function run() {
  console.log("Starting quad outcomes seed...\n");
  const existing = await pool.query("SELECT name FROM body_map_outcomes WHERE body_area_id = 13");
  const existingNames = existing.rows.map((r: any) => r.name);
  let inserted = 0; let skipped = 0;
  for (const o of outcomes) {
    if (existingNames.includes(o.name)) { console.log("SKIP: " + o.name); skipped++; continue; }
    await pool.query(`INSERT INTO body_map_outcomes (body_area_id,name,display_name,priority,is_active,severity_min,severity_max,training_impact,movement_impact,triggers_follow_up,follow_up_question,follow_up_answers,movement_question,movement_options,whats_going_on,training_guidance,daily_movement,desk_work_tips,things_to_watch,check_in_again,show_programme_impact,programme_impact_summary,flagging_movement_patterns,flagging_equipment,flagging_level,flagging_mechanics,flagging_muscles,flagging_exclude_tags,flagging_note,substitution_rules,recommend_recovery_programme,recovery_programme_id,recovery_programme_reason,restore_on_reassessment,reassess_in_days,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,NOW(),NOW())`,
      [o.body_area_id,o.name,o.display_name,o.priority,o.is_active,o.severity_min,o.severity_max,o.training_impact,o.movement_impact,o.triggers_follow_up,o.follow_up_question,o.follow_up_answers?JSON.stringify(o.follow_up_answers):null,o.movement_question,o.movement_options?JSON.stringify(o.movement_options):null,o.whats_going_on,o.training_guidance,o.daily_movement,o.desk_work_tips,o.things_to_watch,o.check_in_again,o.show_programme_impact,o.programme_impact_summary,o.flagging_movement_patterns,o.flagging_equipment,o.flagging_level,o.flagging_mechanics,o.flagging_muscles,o.flagging_exclude_tags,o.flagging_note,o.substitution_rules,o.recommend_recovery_programme,o.recovery_programme_id,o.recovery_programme_reason,o.restore_on_reassessment,o.reassess_in_days]);
    console.log("INSERTED: " + o.name); inserted++;
  }
  console.log("\nDone. " + inserted + " inserted, " + skipped + " skipped.");
  await pool.end();
}
run().catch(err => { console.error("Error:", err.message); process.exit(1); });
